-- record_views_decided_cut (2026-10-02; Michael-gated with PR #865)
--
-- GENERATED by scripts/emit_record_views_decided_cut.py from config.py -- do
-- not hand-edit; regenerate.
--
-- WHY. models.scorer._decide decides on the calibrated probability (and on
-- that minus the deciding price's implied probability) but STORES the raw
-- pair. Discord, push, the health check and the app now cut on the decided
-- numbers (config.decided_cut_sql). These three per-model record views still
-- cut on the raw pair, so a BET the map lifted over the cut would publish but
-- not count, and a BET the map pulled under would count but never publish.
-- This redefines each view's qualify test on the decided numbers. Nothing
-- else in the definitions changes (verbatim from production's
-- pg_get_viewdef, 2026-10-02 4:05 PM ET); the column lists are unchanged, so
-- CREATE OR REPLACE keeps grants.
--
-- The two views over mv_scored_pick_outcomes read the decided numbers off
-- the pick itself (JOIN picks pp ON pp.pick_id = o.pick_id): the matview
-- carries no model_probability_cal / implied columns, and rebuilding it is
-- not needed for a filter change.
--
-- NOT the publish-time guards (price gap, decided-only 24h window): those
-- decide WHEN a pick is announced, not whether it was a bet.
--
-- Guard: each view is skipped once its definition reads
-- model_probability_cal. Registered in data/view_migrations.ACTIVE_MIGRATIONS,
-- so it runs on the first worker pass after merge.
-- ROLLBACK: re-create each view from the definition quoted in PR #865.

DO $mig$
DECLARE
  d text;
BEGIN
  -- ── v_model_full_outcome_picks ─────────────────────────────────────────────
  d := pg_get_viewdef('public.v_model_full_outcome_picks'::regclass, true);
  IF position('model_probability_cal' in d) > 0 THEN
    RAISE NOTICE 'v_model_full_outcome_picks already cuts on the decided numbers - skipping';
  ELSE
    EXECUTE $v$
      CREATE OR REPLACE VIEW public.v_model_full_outcome_picks WITH (security_invoker = on) AS
      SELECT o.pick_id, o.model_id, o.game_date, o.game_id, o.pick_label, o.pick_side,
             o.model_probability, o.edge, o.dk_odds, o.scored_line, o.result,
             o.profit_units, o.decision_book, o.decision_odds, o.decision_edge
      FROM mv_scored_pick_outcomes o
      JOIN model_action_thresholds m ON m.model_id = o.model_id
      JOIN picks pp ON pp.pick_id = o.pick_id
      WHERE ((CASE WHEN pp.model_id IN ('mlb_spread_market', 'mlb_total_market', 'mlb_total_public_fade', 'nfl_live_prop', 'nfl_opener_spread', 'nfl_prop_market', 'nfl_wind_totals', 'nhl_prop_assists', 'nhl_prop_blocked_shots', 'nhl_prop_saves', 'nhl_prop_shots_on_goal', 'wnba_prop_market') THEN pp.model_probability ELSE COALESCE(pp.model_probability_cal, pp.model_probability) END) >= m.min_prob
               AND (m.prob_only = TRUE
                    OR (CASE WHEN pp.model_id IN ('mlb_spread_market', 'mlb_total_market', 'mlb_total_public_fade', 'nfl_live_prop', 'nfl_opener_spread', 'nfl_prop_market', 'nfl_wind_totals', 'nhl_prop_assists', 'nhl_prop_blocked_shots', 'nhl_prop_saves', 'nhl_prop_shots_on_goal', 'wnba_prop_market') THEN COALESCE(pp.decision_edge, pp.edge) WHEN pp.model_id IN ('ncaaf_live_total', 'ncaaf_live_win_prob') THEN COALESCE(pp.model_probability_cal - NULLIF(pp.dk_implied_prob, 0), COALESCE(pp.decision_edge, pp.edge)) ELSE COALESCE(pp.model_probability_cal - COALESCE(NULLIF(pp.decision_implied_prob, 0), NULLIF(pp.dk_implied_prob, 0)), COALESCE(pp.decision_edge, pp.edge)) END) >= COALESCE(m.min_edge, 0)))
        AND (m.min_odds IS NULL OR o.decision_odds IS NULL OR o.decision_odds >= m.min_odds)
    $v$;
  END IF;

  -- ── v_model_full_outcome_record ────────────────────────────────────────────
  d := pg_get_viewdef('public.v_model_full_outcome_record'::regclass, true);
  IF position('model_probability_cal' in d) > 0 THEN
    RAISE NOTICE 'v_model_full_outcome_record already cuts on the decided numbers - skipping';
  ELSE
    EXECUTE $v$
      CREATE OR REPLACE VIEW public.v_model_full_outcome_record WITH (security_invoker = on) AS
      WITH graded AS (
        SELECT o.model_id,
               CASE o.result WHEN 'WIN' THEN 'W' WHEN 'LOSS' THEN 'L' ELSE 'P' END AS res,
               o.decision_odds,
               m.paused,
               m.prob_only,
               o.profit_units AS profit,
               ((CASE WHEN pp.model_id IN ('mlb_spread_market', 'mlb_total_market', 'mlb_total_public_fade', 'nfl_live_prop', 'nfl_opener_spread', 'nfl_prop_market', 'nfl_wind_totals', 'nhl_prop_assists', 'nhl_prop_blocked_shots', 'nhl_prop_saves', 'nhl_prop_shots_on_goal', 'wnba_prop_market') THEN pp.model_probability ELSE COALESCE(pp.model_probability_cal, pp.model_probability) END) >= m.min_prob
               AND (m.prob_only = TRUE
                    OR (CASE WHEN pp.model_id IN ('mlb_spread_market', 'mlb_total_market', 'mlb_total_public_fade', 'nfl_live_prop', 'nfl_opener_spread', 'nfl_prop_market', 'nfl_wind_totals', 'nhl_prop_assists', 'nhl_prop_blocked_shots', 'nhl_prop_saves', 'nhl_prop_shots_on_goal', 'wnba_prop_market') THEN COALESCE(pp.decision_edge, pp.edge) WHEN pp.model_id IN ('ncaaf_live_total', 'ncaaf_live_win_prob') THEN COALESCE(pp.model_probability_cal - NULLIF(pp.dk_implied_prob, 0), COALESCE(pp.decision_edge, pp.edge)) ELSE COALESCE(pp.model_probability_cal - COALESCE(NULLIF(pp.decision_implied_prob, 0), NULLIF(pp.dk_implied_prob, 0)), COALESCE(pp.decision_edge, pp.edge)) END) >= COALESCE(m.min_edge, 0)))
                 AND (m.min_odds IS NULL OR o.decision_odds IS NULL OR o.decision_odds >= m.min_odds) AS passes
        FROM mv_scored_pick_outcomes o
        JOIN model_action_thresholds m ON m.model_id = o.model_id
        JOIN picks pp ON pp.pick_id = o.pick_id
      )
      SELECT model_id,
             bool_or(paused) AS paused,
             bool_or(prob_only) AS prob_only,
             count(*) FILTER (WHERE passes AND res = ANY (ARRAY['W','L','P'])) AS bets,
             count(*) FILTER (WHERE passes AND res = 'W') AS wins,
             count(*) FILTER (WHERE passes AND res = 'L') AS losses,
             count(*) FILTER (WHERE passes AND res = 'P') AS pushes,
             count(*) FILTER (WHERE passes AND res = ANY (ARRAY['W','L','P']) AND decision_odds IS NOT NULL) AS priced_bets,
             CASE WHEN model_id = 'mlb_prop_batter_hr' THEN 0::numeric
                  ELSE round(COALESCE(sum(profit) FILTER (WHERE passes), 0::numeric), 6) END AS units,
             CASE WHEN model_id = 'mlb_prop_batter_hr' THEN NULL::numeric
                  ELSE round(sum(profit) FILTER (WHERE passes)
                             / NULLIF(count(*) FILTER (WHERE passes AND res = ANY (ARRAY['W','L','P'])
                                                       AND decision_odds IS NOT NULL), 0)::numeric
                             * 100::numeric, 1) END AS roi_pct
      FROM graded
      GROUP BY model_id
    $v$;
  END IF;

  -- ── v_model_full_record ────────────────────────────────────────────────────
  d := pg_get_viewdef('public.v_model_full_record'::regclass, true);
  IF position('model_probability_cal' in d) > 0 THEN
    RAISE NOTICE 'v_model_full_record already cuts on the decided numbers - skipping';
  ELSE
    EXECUTE $v$
      CREATE OR REPLACE VIEW public.v_model_full_record WITH (security_invoker = on) AS
      WITH scored AS (
        SELECT p.model_id, p.pick_side,
               (CASE WHEN p.model_id IN ('mlb_spread_market', 'mlb_total_market', 'mlb_total_public_fade', 'nfl_live_prop', 'nfl_opener_spread', 'nfl_prop_market', 'nfl_wind_totals', 'nhl_prop_assists', 'nhl_prop_blocked_shots', 'nhl_prop_saves', 'nhl_prop_shots_on_goal', 'wnba_prop_market') THEN p.model_probability ELSE COALESCE(p.model_probability_cal, p.model_probability) END) AS prob,
               (CASE WHEN p.model_id IN ('mlb_spread_market', 'mlb_total_market', 'mlb_total_public_fade', 'nfl_live_prop', 'nfl_opener_spread', 'nfl_prop_market', 'nfl_wind_totals', 'nhl_prop_assists', 'nhl_prop_blocked_shots', 'nhl_prop_saves', 'nhl_prop_shots_on_goal', 'wnba_prop_market') THEN COALESCE(p.decision_edge, p.edge) WHEN p.model_id IN ('ncaaf_live_total', 'ncaaf_live_win_prob') THEN COALESCE(p.model_probability_cal - NULLIF(p.dk_implied_prob, 0), COALESCE(p.decision_edge, p.edge)) ELSE COALESCE(p.model_probability_cal - COALESCE(NULLIF(p.decision_implied_prob, 0), NULLIF(p.dk_implied_prob, 0)), COALESCE(p.decision_edge, p.edge)) END) AS edge,
               p.scored_line,
               COALESCE(p.decision_odds, p.dk_odds, -110::numeric) AS dk_odds,
               g.home_score, g.away_score, g.home_win_reg, g.went_to_ot,
               g.home_score_f5, g.away_score_f5,
               t.min_prob, t.min_edge, t.prob_only, t.paused,
               CASE
                 WHEN p.model_id LIKE '%f5_moneyline%' THEN 'h2h_1st_5_innings'
                 WHEN p.model_id LIKE '%f5_over_under%' THEN 'totals_1st_5_innings'
                 WHEN p.model_id LIKE '%f5_runline%' THEN 'spreads_1st_5_innings'
                 WHEN p.model_id = 'nhl_moneyline_regulation' THEN 'h2h_3way'
                 WHEN p.model_id LIKE '%over_under%' THEN 'totals'
                 WHEN p.model_id LIKE '%runline%' OR p.model_id LIKE '%puckline%' OR p.model_id LIKE '%spread%' THEN 'spreads'
                 ELSE 'h2h'
               END AS market
        FROM picks p
        JOIN games g ON g.game_id = p.game_id
        JOIN model_action_thresholds t ON t.model_id = p.model_id
        WHERE p.game_date >= '2026-04-14' AND p.is_live IS NOT TRUE AND g.home_score IS NOT NULL
          AND p.model_id NOT LIKE '%prop%' AND p.model_id NOT LIKE 'ufc_%' AND p.model_id NOT LIKE 'golf_%'
      ), ev AS (
        SELECT scored.*,
               CASE WHEN scored.market LIKE '%1st_5_innings' THEN scored.home_score_f5 ELSE scored.home_score END AS sh,
               CASE WHEN scored.market LIKE '%1st_5_innings' THEN scored.away_score_f5 ELSE scored.away_score END AS sa
        FROM scored
      ), o AS (
        SELECT ev.*,
               NOT ev.paused AND ev.prob >= ev.min_prob AND (ev.prob_only OR ev.edge >= ev.min_edge) AS qualifies,
               CASE
                 WHEN ev.sh IS NULL OR ev.sa IS NULL THEN NULL
                 WHEN ev.market = ANY (ARRAY['h2h','h2h_1st_5_innings']) THEN
                   CASE WHEN ev.sh = ev.sa THEN 'PUSH'
                        WHEN ev.pick_side = 'home' AND ev.sh > ev.sa THEN 'WIN'
                        WHEN ev.pick_side = 'away' AND ev.sa > ev.sh THEN 'WIN'
                        ELSE 'LOSS' END
                 WHEN ev.market = 'h2h_3way' THEN
                   CASE WHEN ev.pick_side = 'home' THEN CASE WHEN ev.home_win_reg = 1 THEN 'WIN' ELSE 'LOSS' END
                        WHEN ev.pick_side = 'away' THEN
                          CASE WHEN ev.home_win_reg = 0 AND COALESCE(ev.went_to_ot, 0) = 0 THEN 'WIN' ELSE 'LOSS' END
                        WHEN ev.pick_side = 'draw' THEN CASE WHEN ev.went_to_ot = 1 THEN 'WIN' ELSE 'LOSS' END
                        ELSE NULL END
                 WHEN ev.market = ANY (ARRAY['totals','totals_1st_5_innings']) THEN
                   CASE WHEN ev.scored_line IS NULL THEN NULL
                        WHEN (ev.sh + ev.sa) = ev.scored_line THEN 'PUSH'
                        WHEN ev.pick_side = 'over' AND (ev.sh + ev.sa) > ev.scored_line THEN 'WIN'
                        WHEN ev.pick_side = 'under' AND (ev.sh + ev.sa) < ev.scored_line THEN 'WIN'
                        ELSE 'LOSS' END
                 WHEN ev.market = ANY (ARRAY['spreads','spreads_1st_5_innings']) THEN
                   CASE WHEN ev.scored_line IS NULL THEN NULL
                        WHEN (ev.sh - ev.sa + ev.scored_line) = 0::numeric THEN 'PUSH'
                        WHEN ev.pick_side = 'home' AND (ev.sh - ev.sa + ev.scored_line) > 0::numeric THEN 'WIN'
                        WHEN ev.pick_side = 'away' AND (ev.sh - ev.sa + ev.scored_line) < 0::numeric THEN 'WIN'
                        ELSE 'LOSS' END
                 ELSE NULL
               END AS res
        FROM ev
      )
      SELECT model_id,
             count(*) FILTER (WHERE qualifies AND res = ANY (ARRAY['WIN','LOSS','PUSH'])) AS picks,
             count(*) FILTER (WHERE qualifies AND res = 'WIN') AS wins,
             count(*) FILTER (WHERE qualifies AND res = 'LOSS') AS losses,
             count(*) FILTER (WHERE qualifies AND res = 'PUSH') AS pushes,
             round(sum(CASE WHEN qualifies AND res = 'WIN' THEN
                              CASE WHEN dk_odds > 0::numeric THEN dk_odds / 100.0 ELSE 100.0 / abs(dk_odds) END
                            WHEN qualifies AND res = 'LOSS' THEN -1.0
                            ELSE 0::numeric END), 3) AS profit_units
      FROM o
      GROUP BY model_id
    $v$;
  END IF;
END
$mig$;
