#!/usr/bin/env python3
"""
Recalibrate the opener's per-bet win probability from the snapshot cache.

    python scripts/calibrate_opener.py                       # 2020-2025
    python scripts/calibrate_opener.py --seasons 2023 2025   # the original 3
    python scripts/calibrate_opener.py --emit                # paste-ready table

Wind has `calibrate_lead.py`; the opener had nothing equivalent, so its
DEV_WIN_PROB table could only be regenerated by hand. This does it properly and
prints the numbers that go into `models/opener_spread.py`.

WHAT IT MEASURES
----------------
Two things compose into the table, and the first is the one that is easy to get
wrong:

  1. THE SHRINK. The live card sees |soft - pinnacle NOW|, but a bet is only
     worth its advantage against where Pinnacle CLOSES, and the soft book moves
     most of the way there first. Feeding raw |dev| into the win-probability
     curve overstates it badly.
  2. WHAT THE SHRUNK NUMBER IS WORTH, from the empirical margin-versus-close
     residual distribution — which carries the key-number atoms, so the curve
     has flat stretches rather than being smooth.

Plus the measured Pinnacle-direction excess, pooled over the sample.

The check that matters is at the bottom: applying the fitted curve back to the
selected bets should reproduce the realised win rate. If it does not, the
composition is wrong and nothing downstream should be trusted.

Zero Odds API credits — everything comes from data/processed/dev_long.parquet.
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import sys

import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
sys.path.insert(0, PKG)
sys.path.insert(0, HERE)

# Deviation buckets for the shrink measurement. Deliberately coarse: 70% of all
# selected bets sit at exactly 1.0, so fine bins above 3 would be noise.
DEV_BUCKETS = [0.99, 1.25, 1.75, 2.25, 3.0, 99.0]
GRID = np.arange(1.0, 8.01, 0.5)


def _load_backtest():
    spec = importlib.util.spec_from_file_location(
        "bo_cal", os.path.join(HERE, "backtest_opener.py"))
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod
    spec.loader.exec_module(mod)
    mod.RESID = mod.residuals()
    return mod


def selected_bets(bo, seasons, threshold: float) -> pd.DataFrame:
    w = bo.price(bo.load("spreads", "pinnacle", 48.0, 168.0, seasons), "spreads")
    q = w[w.adev >= threshold]
    s = (q.sort_values(["game_id", "snap_ts", "adev", "book"],
                       ascending=[True, True, False, True])
         .groupby("game_id", as_index=False).first()).copy()
    return s[s.win != 0.5].reset_index(drop=True)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seasons", type=int, nargs=2, default=[2020, 2025])
    ap.add_argument("--threshold", type=float, default=1.0)
    ap.add_argument("--emit", action="store_true", help="print a paste-ready dict")
    a = ap.parse_args()

    bo = _load_backtest()
    s = selected_bets(bo, a.seasons, a.threshold)
    lo, hi = a.seasons
    print(f"=== OPENER CALIBRATION, {lo}-{hi}, |dev| >= {a.threshold} ===")
    print(f"  {len(s)} decided bets across {s.game_id.nunique()} games, "
          f"{s.book.nunique()} books")
    print(f"  seasons present: {sorted(int(x) for x in s.season.unique())}")

    # ---- 1. the shrink -----------------------------------------------------
    print(f"\n--- deviation seen at bet time vs advantage actually realised ---")
    s["db"] = pd.cut(s.adev, DEV_BUCKETS)
    t = s.groupby("db", observed=True).agg(
        n=("clv", "size"), dev=("adev", "mean"), clv=("clv", "mean"),
        win=("win", "mean")).reset_index()
    t["shrink"] = (t.clv / t.dev).round(3)
    t["dev"] = t.dev.round(3)
    t["clv"] = t.clv.round(3)
    t["win"] = (t.win * 100).round(2)
    print(t.to_string(index=False))
    print(f"  overall: mean |dev| {s.adev.mean():.3f} -> mean realised CLV "
          f"{s.clv.mean():.3f}  (shrink {s.clv.mean()/s.adev.mean():.3f})")

    knot_dev = t.dev.tolist()
    knot_shrink = [min(float(x), 1.0) for x in t.shrink.tolist()]

    def expected_clv(d):
        d = np.asarray(d, dtype=float)
        return d * np.clip(np.interp(d, knot_dev, knot_shrink), 0.50, 1.0)

    # ---- 2. the excess -----------------------------------------------------
    pos = s.bet_home.values
    exp_from_number = bo.exp_win(s.clv.values, "spreads", pos)
    excess = float(s.win.mean() - exp_from_number.mean())
    print(f"\n--- the Pinnacle-direction excess ---")
    print(f"  realised win rate       {s.win.mean()*100:.2f}%")
    print(f"  expected from the number {exp_from_number.mean()*100:.2f}%")
    print(f"  EXCESS                  {excess*100:+.2f}pp")

    # ---- 3. the table ------------------------------------------------------
    probs = bo.exp_win(expected_clv(GRID), "spreads",
                       np.ones(len(GRID), dtype=bool)) + excess
    print(f"\n--- DEV_WIN_PROB ---")
    for d, p in zip(GRID, probs):
        print(f"  |dev| {d:>4.1f} -> expected CLV {expected_clv([d])[0]:5.2f} "
              f"-> P(win) {p:.4f}")

    # ---- 4. the check that matters ----------------------------------------
    fitted = bo.exp_win(expected_clv(s.adev.values), "spreads",
                        np.ones(len(s), dtype=bool)) + excess
    print(f"\n--- VALIDATION ---")
    print(f"  pooled modelled P {fitted.mean()*100:.2f}%  vs realised "
          f"{s.win.mean()*100:.2f}%   (gap {abs(fitted.mean()-s.win.mean())*100:.2f}pp)")
    if abs(fitted.mean() - s.win.mean()) > 0.01:
        print("  WARNING: gap above 1pp — the composition is off, do not ship this table")

    print(f"\n  by season:")
    s["p_fit"] = fitted
    for ssn, g in s.groupby("season"):
        print(f"    {int(ssn)}: n={len(g):4d} modelled {g.p_fit.mean()*100:5.2f}% "
              f"realised {g.win.mean()*100:5.2f}%")

    if a.emit:
        print("\nDEV_WIN_PROB = {")
        line = "    "
        for i, (d, p) in enumerate(zip(GRID, probs)):
            line += f"{d}: {p:.4f}, "
            if (i + 1) % 5 == 0:
                print(line.rstrip())
                line = "    "
        if line.strip():
            print(line.rstrip())
        print("}")
        print(f"\n# knots: {[round(x,2) for x in knot_dev]} -> "
              f"{[round(x,3) for x in knot_shrink]}")
        print(f"# excess: {excess:.4f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
